<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <RootNamespace>Zarem.RiscV.Linker</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Zarem.Linker\Zarem.Linker.csproj" />
    <ProjectReference Include="..\Zarem.RiscV.Assembler\Zarem.RiscV.Assembler.csproj" />
  </ItemGroup>

</Project>
