<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <RootNamespace>Zarem.Emulator</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Instructions\BaseSet\BType.inst.json" />
    <EmbeddedResource Include="Resources\Instructions\BaseSet\IType.inst.json" />
    <EmbeddedResource Include="Resources\Instructions\BaseSet\JType.inst.json" />
    <EmbeddedResource Include="Resources\Instructions\BaseSet\RType.inst.json" />
    <EmbeddedResource Include="Resources\Instructions\BaseSet\SType.inst.json" />
    <EmbeddedResource Include="Resources\Instructions\BaseSet\UType.inst.json" />
    <EmbeddedResource Include="Resources\Instructions\MultiplicationSet\RType.inst.json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Zarem.Assembler\Zarem.Assembler.csproj" />
    <ProjectReference Include="..\Zarem.RiscV.Base\Zarem.RiscV.Base.csproj" />
  </ItemGroup>

</Project>
