<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<GenerateDocumentationFile>false</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\..\src\Archs\Mips\Zarem.Mips.Assembler\Zarem.Mips.Assembler.csproj" />
	  <ProjectReference Include="..\..\..\src\Archs\Mips\Zarem.Mips.Linker\Zarem.Mips.Linker.csproj" />
	  <ProjectReference Include="..\..\..\src\Zarem.Assembler\Zarem.Assembler.csproj" />
	  <ProjectReference Include="..\..\Archs\MIPS\Test.MIPS\Test.Mips.csproj" />
	</ItemGroup>

</Project>
