<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<GenerateDocumentationFile>false</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\..\src\Archs\MIPS\Zarem.Assembler.MIPS\Zarem.Assembler.Mips.csproj" />
	  <ProjectReference Include="..\..\..\src\Archs\MIPS\Zarem.Linker.MIPS\Zarem.Linker.Mips.csproj" />
	  <ProjectReference Include="..\..\..\src\Zarem.Assembler\Zarem.Assembler.csproj" />
	  <ProjectReference Include="..\..\Archs\MIPS\Test.MIPS\Test.Mips.csproj" />
	</ItemGroup>

</Project>
