<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <RootNamespace>Zarem.Debugger</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
  	  <ProjectReference Include="..\Zarem.Base\Zarem.Base.csproj" />
  	  <ProjectReference Include="..\Zarem.Emulator\Zarem.Emulator.csproj" />
  </ItemGroup>
	
</Project>
