<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <IsPackable>false</IsPackable>
	  <IsTestProject>true</IsTestProject>
	  <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Test.MIPS\Test.MIPS.csproj" />
  </ItemGroup>

</Project>
