<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
		<GenerateDocumentationFile>false</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
		<PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.8.0" />
		<PackageReference Include="Microsoft.Testing.Extensions.TrxReport" Version="1.4.3" />
		<PackageReference Include="MSTest" Version="3.6.4" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\..\src\Archs\RiscV\Zarem.RiscV.Assembler\Zarem.RiscV.Assembler.csproj" />
		<ProjectReference Include="..\..\..\..\src\Archs\RiscV\Zarem.RiscV.Emulator\Zarem.RiscV.Emulator.csproj" />
		<ProjectReference Include="..\..\..\..\src\Archs\RiscV\Zarem.RiscV.Base\Zarem.RiscV.Base.csproj" />
		<ProjectReference Include="..\..\..\Test.Zarem\Test.Zarem.csproj" />
		<ProjectReference Include="..\..\Test.Archs\Test.Archs.csproj" />
	</ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

</Project>
