<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <RootNamespace>Zarem.Emulator</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Silk.NET.Direct3D11" Version="2.23.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Zarem.Emulator\Zarem.Emulator.csproj" />
  </ItemGroup>

</Project>
