<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Nullable>enable</Nullable>
    <RootNamespace>Zarem.IDE</RootNamespace>
    <Configurations>Debug;Release;Alpha</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\ColorSchemes\Autumn.json" />
    <EmbeddedResource Include="Resources\ColorSchemes\Winter.json" />
    <EmbeddedResource Include="Resources\ColorSchemes\Terminal-Dark.json" />
    <EmbeddedResource Include="Resources\ColorSchemes\Terminal-Light.json" />
    <EmbeddedResource Include="Resources\ColorSchemes\Zarem-Dark.json" />
    <EmbeddedResource Include="Resources\ColorSchemes\Zarem-Light.json" />
    <EmbeddedResource Include="Resources\EncodingPatterns\UniqueEncodings.json" />
    <EmbeddedResource Include="Resources\EncodingPatterns\CoProcessor0Encodings.json" />
    <EmbeddedResource Include="Resources\EncodingPatterns\CoProcessor1Encodings.json" />
    <EmbeddedResource Include="Resources\EncodingPatterns\PrimaryEncodings.json" />
    <EmbeddedResource Include="Resources\Instructions\FloatInstructions.json" />
    <EmbeddedResource Include="Resources\Instructions\SpecializedInstructions.json" />
    <EmbeddedResource Include="Resources\Instructions\CoProc0Instructions.json" />
    <EmbeddedResource Include="Resources\Instructions\CommonInstructions.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Archs\MIPS\Zarem.MIPS\Zarem.MIPS.csproj" />
    <ProjectReference Include="..\..\ModuleFormats\Zarem.ELF\Zarem.ELF.csproj" />
    <ProjectReference Include="..\..\ModuleFormats\Zarem.RASM\Zarem.RASM.csproj" />
  </ItemGroup>

</Project>
