<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <RootNamespace>Zarem.MIPS</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Zarem\Zarem.csproj" />
    <ProjectReference Include="..\Zarem.Assembler.MIPS\Zarem.Assembler.MIPS.csproj" />
    <ProjectReference Include="..\Zarem.Emulator.MIPS\Zarem.Emulator.MIPS.csproj" />
    <ProjectReference Include="..\Zarem.Linker.MIPS\Zarem.Linker.MIPS.csproj" />
  </ItemGroup>

</Project>
