<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<RootNamespace>Zarem.Mips.Emulator</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\Zarem.Emulator\Zarem.Emulator.csproj" />
		<ProjectReference Include="..\Zarem.MIPS.Base\Zarem.Mips.Base.csproj" />
	</ItemGroup>

</Project>
