<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <RootNamespace>Zarem</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Zarem.Assembler\Zarem.Assembler.csproj" />
    <ProjectReference Include="..\Zarem.CheatSheet\Zarem.CheatSheet.csproj" />
    <ProjectReference Include="..\Zarem.Debugger\Zarem.Debugger.csproj" />
    <ProjectReference Include="..\Zarem.Disassembler\Zarem.Disassembler.csproj" />
    <ProjectReference Include="..\Zarem.Emulator\Zarem.Emulator.csproj" />
    <ProjectReference Include="..\Zarem.Linker\Zarem.Linker.csproj" />
  </ItemGroup>

</Project>
