<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <RootNamespace>Zarem</RootNamespace>
	  <Configurations>Debug;Release;Alpha</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Zarem.Emulator\Zarem.Emulator.csproj" />
    <ProjectReference Include="..\Zarem.Linker\Zarem.Linker.csproj" />
  </ItemGroup>

</Project>
