<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <RootNamespace>Zarem.RiscV.CheatSheet</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="EncodingPatterns.json" />
    <EmbeddedResource Include="InstructionCollections.json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Zarem.CheatSheet\Zarem.CheatSheet.csproj" />
    <ProjectReference Include="..\Zarem.RiscV.Base\Zarem.RiscV.Base.csproj" />
  </ItemGroup>

</Project>
