<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <RootNamespace>Zarem.RiscV</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ModelingEvolution.JsonParsableConverter" Version="1.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Zarem.Base\Zarem.Base.csproj" />
  </ItemGroup>

</Project>
