<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <RootNamespace>Zarem.RiscV</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Zarem\Zarem.csproj" />
    <ProjectReference Include="..\Zarem.RiscV.Assembler\Zarem.RiscV.Assembler.csproj" />
    <ProjectReference Include="..\Zarem.RiscV.CheatSheet\Zarem.RiscV.CheatSheet.csproj" />
    <ProjectReference Include="..\Zarem.RiscV.Debugger\Zarem.RiscV.Debugger.csproj" />
    <ProjectReference Include="..\Zarem.RiscV.Emulator\Zarem.RiscV.Emulator.csproj" />
    <ProjectReference Include="..\Zarem.RiscV.Linker\Zarem.RiscV.Linker.csproj" />
  </ItemGroup>

</Project>
