<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <RootNamespace>Zarem.RiscV</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Zarem\Zarem.csproj" />
    <ProjectReference Include="..\Zarem.Assembler.RiscV\Zarem.RiscV.Assembler.csproj" />
    <ProjectReference Include="..\Zarem.Debugger.RiscV\Zarem.RiscV.Debugger.csproj" />
    <ProjectReference Include="..\Zarem.Emulator.RiscV\Zarem.RiscV.Emulator.csproj" />
    <ProjectReference Include="..\Zarem.Linker.RiscV\Zarem.RiscV.Linker.csproj" />
  </ItemGroup>

</Project>
