<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Nullable>enable</Nullable>
    <RootNamespace>Zarem.IDE</RootNamespace>
    <Configurations>Debug;Release;Alpha</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\ColorSchemes\Autumn.json" />
    <EmbeddedResource Include="Resources\ColorSchemes\Winter.json" />
    <EmbeddedResource Include="Resources\ColorSchemes\Terminal-Dark.json" />
    <EmbeddedResource Include="Resources\ColorSchemes\Terminal-Light.json" />
    <EmbeddedResource Include="Resources\ColorSchemes\Zarem-Dark.json" />
    <EmbeddedResource Include="Resources\ColorSchemes\Zarem-Light.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Archs\MIPS\Zarem.MIPS\Zarem.Mips.csproj" />
    <ProjectReference Include="..\..\..\Archs\RiscV\Zarem.RiscV\Zarem.RiscV.csproj" />
    <ProjectReference Include="..\..\..\ModuleFormats\Zarem.ELF\Zarem.Elf.csproj" />
  </ItemGroup>

</Project>
