<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <RootNamespace>Zarem.Assembler</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Instructions\CoProcessor1Instructions.json" />
    <EmbeddedResource Include="Resources\Instructions\FloatingPointInstructions.json" />
    <EmbeddedResource Include="Resources\Instructions\CoProcessor0Instructions.json" />
    <EmbeddedResource Include="Resources\Instructions\ITypeInstructions.json" />
    <EmbeddedResource Include="Resources\Instructions\JTypeInstructions.json" />
    <EmbeddedResource Include="Resources\Instructions\PseudoInstructions.json" />
    <EmbeddedResource Include="Resources\Instructions\RegImmInstructions.json" />
    <EmbeddedResource Include="Resources\Instructions\RTypeInstructions.json" />
    <EmbeddedResource Include="Resources\Instructions\Special2Instructions.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Localization" Version="9.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Zarem.Assembler\Zarem.Assembler.csproj" />
    <ProjectReference Include="..\Zarem.MIPS.Base\Zarem.MIPS.Base.csproj" />
  </ItemGroup>

</Project>
