<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <RootNamespace>Zarem.N64</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Archs\Mips\Zarem.Mips.Emulator\Zarem.Mips.Emulator.csproj" />
    <ProjectReference Include="..\..\..\Zarem.Emulator.DirectX\Zarem.Emulator.DirectX.csproj" />
  </ItemGroup>

</Project>
