<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <RootNamespace>Zarem.Debugger</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Zarem.Debugger\Zarem.Debugger.csproj" />
    <ProjectReference Include="..\Zarem.Assembler.MIPS\Zarem.Assembler.Mips.csproj" />
    <ProjectReference Include="..\Zarem.Emulator.MIPS\Zarem.Emulator.Mips.csproj" />
    <ProjectReference Include="..\Zarem.MIPS.Base\Zarem.Mips.Base.csproj" />
  </ItemGroup>

</Project>
