<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<RootNamespace>Zarem.Console</RootNamespace>
		<ImplicitUsings>enable</ImplicitUsings>
		<Configurations>Debug;Release;Alpha</Configurations>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Spectre.Console" Version="0.54.0" />
		<PackageReference Include="System.CommandLine" Version="2.0.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Archs\MIPS\Zarem.MIPS\Zarem.Mips.csproj" />
		<ProjectReference Include="..\..\ModuleFormats\Zarem.ELF\Zarem.Elf.csproj" />
	</ItemGroup>

</Project>
