<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows10.0.22621.0</TargetFramework>
		<TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
		<GenerateDocumentationFile>false</GenerateDocumentationFile>
		<RootNamespace>Zarem.WinUI</RootNamespace>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<Platforms>x64;ARM64</Platforms>
		<RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
		<PublishProfile>$(Platform).pubxml</PublishProfile>
		<UseWinUI>true</UseWinUI>
		<EnablePreviewMsixTooling>true</EnablePreviewMsixTooling>
		<WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
		<Configurations>Debug;Release;Alpha</Configurations>
	</PropertyGroup>
	<ItemGroup>
	  <None Remove="Controls\RunningIndicator.xaml" />
	  <None Remove="Services\Popup\TextInputPopup.xaml" />
	</ItemGroup>
	<ItemGroup>
	  <AppxManifest Include="Package.appxmanifest" Condition="'$(Configuration)' == 'Release'">
	    <SubType>Designer</SubType>
	  </AppxManifest>
	  <AppxManifest Include="Package-Alpha.appxmanifest" Condition="'$(Configuration)' == 'Alpha'">
	    <SubType>Designer</SubType>
	  </AppxManifest>
	  <AppxManifest Include="Package-Dev.appxmanifest" Condition="'$(Configuration)' == 'Debug'">
	    <SubType>Designer</SubType>
	  </AppxManifest>
	</ItemGroup>
	
	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Labs.WinUI.ColorAnalyzer" Version="0.1.251101-build.2372" />
		<PackageReference Include="CommunityToolkit.Labs.WinUI.Controls.DataTable" Version="0.1.251101-build.2372" />
		<PackageReference Include="CommunityToolkit.Labs.WinUI.Controls.Marquee" Version="0.1.251101-build.2372" />
		<PackageReference Include="CommunityToolkit.Labs.WinUI.Controls.OpacityMaskView" Version="0.1.251101-build.2372" />
		<PackageReference Include="CommunityToolkit.WinUI.Behaviors" Version="8.2.251219" />
		<PackageReference Include="CommunityToolkit.WinUI.Controls.Primitives" Version="8.2.251219" />
		<PackageReference Include="CommunityToolkit.WinUI.Controls.Segmented" Version="8.2.251219" />
		<PackageReference Include="CommunityToolkit.WinUI.Controls.SettingsControls" Version="8.2.251219" />
		<PackageReference Include="CommunityToolkit.WinUI.Controls.Sizers" Version="8.2.251219" />
		<PackageReference Include="CommunityToolkit.WinUI.Converters" Version="8.2.251219" />
		<PackageReference Include="CommunityToolkit.WinUI.Extensions" Version="8.2.251219" />
		<PackageReference Include="GitInfo" Version="3.6.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="HexBox.WinUI" Version="0.2.3" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.10" />
		<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.6.250108002" />
		<PackageReference Include="Microsoft.Windows.CsWinRT" Version="2.2.0" />
		<PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.6901" />
		<PackageReference Include="Microsoft.Xaml.Behaviors.WinUI.Managed" Version="3.0.0" />
		<Manifest Include="$(ApplicationManifest)" />
	</ItemGroup>

	<PropertyGroup>
		<CsWinRTIncludes>WinUIEditor</CsWinRTIncludes>
		<GenerateTemporaryStoreCertificate>True</GenerateTemporaryStoreCertificate>
		<GenerateAppInstallerFile>False</GenerateAppInstallerFile>
		<AppxPackageSigningEnabled>True</AppxPackageSigningEnabled>
		<AppxPackageSigningTimestampDigestAlgorithm>SHA256</AppxPackageSigningTimestampDigestAlgorithm>
		<AppxAutoIncrementPackageRevision>False</AppxAutoIncrementPackageRevision>
		<AppxSymbolPackageEnabled>True</AppxSymbolPackageEnabled>
		<GenerateTestArtifacts>True</GenerateTestArtifacts>
		<AppxBundle>Always</AppxBundle>
		<AppxBundlePlatforms>x64|arm64</AppxBundlePlatforms>
		<HoursBetweenUpdateChecks>0</HoursBetweenUpdateChecks>
		<PackageCertificateThumbprint>3C27F89D4FC0DDE41BB77C54D790A32DAD4330F7</PackageCertificateThumbprint>
		<NeutralLanguage>en-US</NeutralLanguage>
		<DefaultLanguage>en</DefaultLanguage>
	</PropertyGroup>

	<!-- 
    Defining the "Msix" ProjectCapability here allows the Single-project MSIX Packaging
    Tools extension to be activated for this project even if the Windows App SDK Nuget
    package has not yet been restored.
  -->
	<ItemGroup Condition="'$(DisableMsixProjectCapabilityAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
		<ProjectCapability Include="Msix" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\submodules\WinUIEdit\WinUIEditor\WinUIEditor.vcxproj" />
		<ProjectReference Include="..\Zarem.IDE.ViewModels\Zarem.IDE.ViewModels.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Page Update="Services\Popup\TextInputPopup.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>

	<ItemGroup>
	  <Page Update="Controls\RunningIndicator.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
</Project>
